### PR TITLE
Use cargo workplaces

### PR DESCRIPTION
**Pull request by paulrouget**
I managed to remove all the warnings.

Please let me know if there's any changes you're not happy with:

- created 5 crates: core lib, plato, emulator, fetcher and importer.
- only one structure needed migration (from plato to core): Context
- i moved mupdf wrapper outside of the rust code, and build it binary within target directory for cleanness reasons
- removed never used code

I'm still having this warning when cross compiling.

More details [here](https://doc.rust-lang.org/beta/nightly-rustc/src/rustc_codegen_llvm/llvm_util.rs.html#391) and [here](https://github.com/rust-lang/rust/issues/96472).

```
warning: unknown feature specified for `-Ctarget-feature`: `a9`
  |
  = note: it is still passed through to the codegen backend
  = note: consider filing a feature request
```

### CODE REVIEW

**Comment by paulrouget** [comment]
Fix #262

**Comment by baskerville** [comment]
Thanks!

I've only found a small mistake in `service.sh` for the `install_importer` case: the correct invocation is `cargo install --path crates/importer "$@"` and not `cargo install --path . -p plato-importer "$@"`.

Regarding the remaining warning, I think I understand why it shows a warning: in the output of `rustc --print target-features --target arm-unknown-linux-gnueabihf`, *a9* isn't in the *rustc* table (but is in the *LLVM* table) while all the other features used in `.cargo/config` (*v7*, *vfp3*, *neon*) are in the *rustc* table.

**Comment by paulrouget** [comment]
> I've only found a small mistake in service.sh

Fixed

> Regarding the remaining warning

I'll file a rustc issue for that. Thank you.

**Comment by baskerville** [comment]
I'm getting a few errors when I try to build the article fetcher with `cargo +nightly build --profile release-minsized -Z build-std=std,panic_abort --target arm-unknown-linux-gnueabihf -p fetcher` (for example: `error: cannot determine resolution for the macro json`).

**Comment by baskerville** [comment]
What seems to be causing it is `-Z build-std=std,panic_abort`.

**Comment by paulrouget** [comment]
I've seen that before. I think it's a crate name mixup. `core::` show be renamed. I'll give it a try later.

**Comment by paulrouget** [comment]
@baskerville can you try with the last commit?

**Pull request closed without merging**
