### PR TITLE
Article Fetcher usability improvements and documentation

### PR DESCRIPTION
**Pull request by welps**
This PR presents the following changes:

- Documentation making the article fetcher (which is a killer feature!) more visible with instructions on how to set it up and use it.
- Expand certain errors and more importantly displaying them to the user through the notification system. (This is actually why I wasn't able to get it to work initially, I'm an idiot and had a typo)
- Change the fetcher call to request metadata only, I've upped the `perPage` count to `100` since we no longer pull in the `content` field. An example call on my end for the full data with 8 entries returned a 160KB response, a metadata only call for 150 entries returns roughly the same.

### CODE REVIEW

**Comment by welps** [comment]
@baskerville Let me know your thoughts on these changes, thanks!

**Comment by baskerville** [comment]
> * Documentation making the article fetcher (which is a killer feature!) more visible with instructions on how to set it up and use it.

I think it's fine to mention the hooks in the README. `HOOKS.md` already mentions the example fetcher. The documentation for the fetcher is too verbose in comparison to the existing documentation.

> * Expand certain errors and more importantly displaying them to the user through the notification system. (This is actually why I wasn't able to get it to work initially, I'm an idiot and had a typo)

We currently send every error to `info.log`. I'm not sure why I would suddenly break this pattern? I'm fine with making the error more explicit though.

> * Change the fetcher call to request metadata only, I've upped the `perPage` count to `100` since we no longer pull in the `content` field. An example call on my end for the full data with 8 entries returned a 160KB response, a metadata only call for 150 entries returns roughly the same.

The *detail* parameter is only available in 2.4.0. I'm still using framabag.org (it will disappear in July 2021) which uses 2.3.3.

**Comment by welps** [comment]
> I think it's fine to mention the hooks in the README. HOOKS.md already mentions the example fetcher. The documentation for the fetcher is too verbose in comparison to the existing documentation.

> We currently send every error to info.log. I'm not sure why I would suddenly break this pattern? I'm fine with making the error more explicit though.

I'm not sure how many people use the fetcher right now, but these changes encourage use and enhance usability of the fetcher. In my own case, I had been using wallabako because I wasn't even aware this feature existed until you mentioned it. 

When I did set it up, the fetcher ran, and I saw nothing on my kobo. Is it running? Did it complete successfully or fail? Having to check `info.log` to find any of this information *as a first time user* is discouraging. Do we see a downside to exposing the errors through the notification system?

I know the fetcher doc may seem too verbose, but maybe the rest of the documentation isn't verbose enough? I know that you're very responsive on the mobileread forums, but some of the (repeated) questions can be addressed through more comprehensive documentation with the benefit of training the user to reference documentation first! This is certainly my approach at the past several orgs I've worked at, drastically reducing the time I personally spend answering questions.

 > The detail parameter is only available in 2.4.0. I'm still using framabag.org (it will disappear in July 2021) which uses 2.3.3.

OK, this is my bad for sure. I will address this.

**Comment by welps** [comment]
> The detail parameter is only available in 2.4.0. I'm still using framabag.org (it will disappear in July 2021) which uses 2.3.3.

e30f948 provides a check against the `/api/version` or `/api/info` endpoints, as the former is deprecated as of `2.4.0`. We'll provide the updated parameters (100 per page with metadata only) if the wallabag API registers as `2.4.0` or greater.

The GitHub Actions builds are currently breaking due to changes from master, I will address this in a separate PR.

**Comment by welps** [comment]
@baskerville Requested changes were made

**Comment by welps** [comment]
@baskerville I've added tests to hopefully make these changes more palatable, but I'm happy to address or try to understand any concerns you may still have. I'm still using wallabako, but I really would like to switch over to your article fetcher and this is a step towards that. 

Provided you are amicable to such changes, I would like to pursue adding the following **optional** features as well:
* an option to limit to how many articles reside on the device
    * I have over 2k articles "to catch up on" which is certainly my problem, but maybe this is not uncommon to people
* an option to remove read articles from the device and my wallabag account 
    *  this is primarily why i still use wallabako

**Comment by baskerville** [comment]
> * an option to remove read articles from the device and my wallabag account

I've made a step towards this in 2ec71e435644ddb4644525c1ccc6da5b4d3b29e1.

We'll then want to let the fetcher communicate with *Plato* (through a socket) and ask for the list of read documents inside the hook's path.

**Comment by baskerville** [comment]
> ask for the list of read documents inside the hook's path.

As of b151712f5b62836f1f2eb2a6340f5f8fe967f51e, this can be achieved with the following event:
```rust
json!({"type": "search", "path": save_path, "query": "'F"})
```

**Comment by welps** [comment]
Oh wow, that's incredible. Thanks for the quick turnaround.

**Comment by baskerville** [comment]
I've come up with a shorter version of `is_detail_available`:
```rust
fn is_detail_available(client: &Client, settings: &Settings) -> bool {
    // /api/info is only available in 2.4.0 and up.
    let url = format!("{}/api/info", settings.base_url);
    client.get(&url).send()
          .map_or(false, |response| response.status().is_success())
}
```

**Comment by welps** [comment]
@baskerville Very elegant, makes sense. Thank you.

**Comment by baskerville** [comment]
I've added the following settings in 4315c4aa16ec554e768ab95e31aed4da9555c164:
```toml
# Mark the finished articles as read on the server.
sync-finished = false

# Remove the finished articles from the device.
remove-finished = false

# Limit the difference between the number of downloaded articles and the
# number of removed articles. *0* means *∞*. Once that limit is reached,
# new articles will no longer be downloaded.
balance-limit = 0
```

**Comment by welps** [comment]
While I appreciate that you did the work, I honestly wish this was a more collaborative experience and was given information on what I can improve on to make this PR acceptable.

**Pull request closed without merging**
