### PR TITLE
Port to Remarkable Tablet

### PR DESCRIPTION
**Pull request by darvin**
https://remarkable.com/
http://remarkablewiki.com/
https://github.com/canselcik/libremarkable

This is WIP of port to Remarkable.
Creating pull request early to discuss acceptance into upstream and refactoring/changes needed for that.

Current status:
- [x] **Battery**: done, implemented as separate _RemarkableBattery_
- [x] **Multitouch/buttons events**: done (thank you so much for the patch), implemented as separate _remarkable_parse_device_events_ (kobo specific _parse_device_events_ moved to _kobo_parse_device_events_).
  - Should we generalize it? I feel we should not, remarkable driver definitely generates events weirdly.
  - [x] Remarkable has left and right buttons, support needed for next/previous page. Should be easy.

- [x] **Framebuffer** - almost works, implemented as separate _RemarkableFramebuffer_, uses libremarkable
  -  [ ] Even tho drawing is quite good right now, there are still some artifacts, I probably dont refresh it properly. 
  -  [x] DPI is set for 300, if i try to set it to actual DPI of remarkable - 226 (or on some other CURRENT_DEVICE dims/dpi combinations), it crashes without backtrace. Those dims are only used in drawing of GUI, actual framebuffer code only relies on native resolution of framebuffer, so im not sure whatsup

- [ ] **Power** - Remarkable screen apparenly needs a framebuffer command to power off/on, shell script approach wont work: https://github.com/canselcik/libremarkable/issues/7 . Planning to use libremarkable for that

- [ ] ~~**CURRENT_DEVICE** - Right now Remarkable Device is implemented like kinda another kind of Kobo device, what should i do? Maybe Trait _Device_ with 2 stucts implementing this trait - _KoboDevice_ and _RemarkableDevice_?.. please advice~~
- [ ] ~~**Build system** - 2 build scripts? 1 script with parameter? 2 products? Please advice~~
- [ ] **Cleanup and warnings**

Nice to haves:

 - [ ] Hide a backlight button if device has no backlight
 - [ ] Wacom pen. I'm not sure i should implement it to be honest or how it really should behave
 - [ ] Native book library. Remarkable has cloud-synced library. Files are renamed into nasty UUIDs, but next to them there are jsons with metadata.

### CODE REVIEW

**Comment by baskerville** [comment]
> DPI is set for 300, if i try to set it to actual DPI of remarkable - 226 (or on some other CURRENT_DEVICE dims/dpi combinations), it crashes without backtrace. Those dims are only used in drawing of GUI, actual framebuffer code only relies on native resolution of framebuffer, so im not sure whatsup

You'll only get a useful backtrace from a debug build.

But that won't be necessary. I think I know the fix:
Set the DPI back to 226 and add the following entry to `BAR_SIZES` (in `device.rs`):
```rust
((1872, 226), (91, 123)),
```

> Creating pull request early to discuss acceptance into upstream and refactoring/changes needed for that.

I'm fine with helping you do the port but I'm not interested in merging the changes.

It's already enough trouble for me dealing with all the *Kobo* devices.

**Comment by darvin** [comment]
Thank you so much for your help! Its completely understandable.

...Maybe separating device dependent functionality into separate project could be useful?...

**Comment by darvin** [comment]
img_3836
img_5080
what do you think could cause such artifact?

```
update (mode Full)
update completed -> 1
wait token 1
wait completed -> 0

update (mode Gui)
update completed -> 2
wait token 2
wait completed -> 0

update (mode Gui)
update completed -> 3
update (mode Gui)
update completed -> 4
wait token 4
wait completed -> 0

wait token 3
wait completed -> 0

update (mode Partial)
update completed -> 5
wait token 5
wait completed -> 0

update (mode Gui)
update completed -> 6
wait token 6
wait completed -> 0

update (mode Partial)
update completed -> 7
wait token 7
wait completed -> 0

update (mode Gui)
update completed -> 8
update (mode Gui)
update completed -> 9
update (mode Fast)
update completed -> 10
wait token 10
wait completed -> 0

update (mode Gui)
update completed -> 11
wait token 8
wait completed -> 0

wait token 11
wait completed -> 0

wait token 9
wait completed -> 0

update (mode Partial)
update completed -> 12
wait token 12
wait completed -> 0

update (mode Gui)
update completed -> 13
update (mode Gui)
update completed -> 14
wait token 14
wait completed -> 0

wait token 13
wait completed -> 0

update (mode Partial)
update completed -> 15
wait token 15
wait completed -> 0

update (mode Gui)
update completed -> 16
update (mode Gui)
update completed -> 17
update (mode Gui)
update completed -> 18
wait token 17
wait completed -> 0

wait token 18
wait completed -> 0

wait token 16
wait completed -> 0

update (mode Partial)
update completed -> 19
wait token 19
wait completed -> 0

update (mode Gui)
update completed -> 20
update (mode Gui)
update completed -> 21
wait token 21
wait completed -> 0

wait token 20
wait completed -> 0

update (mode Partial)
update completed -> 22
wait token 22
wait completed -> 0

update (mode Gui)
update completed -> 23
update (mode Gui)
update completed -> 24
update (mode Gui)
update completed -> 25
wait token 25
wait completed -> 0

update (mode Gui)
update completed -> 26
```

also, am i wrong in assumption that code should call wait(token) on framebuffer after each update?...

**Comment by baskerville** [comment]
*Plato* only waits when it needs to (to avoid collisions).

It would seem you have mapped every update mode to the same waveform: `WAVEFORM_MODE_GC16_FAST`.

`WAVEFORM_MODE_GC16_FAST` seems appropriate for `Gui`. But `WAVEFORM_MODE_GC16` appears to be more appropriate for `Partial` and `Full`. Not sure about `Fast` and `FastMono`, because `WAVEFORM_MODE_GLR16` seems to only do full refreshes.

**Comment by darvin** [comment]
fixed the framebuffer bugs, it was an errors in my color calculating code

**Pull request closed without merging**
